# fly.toml app configuration file generated for testing-u7jy1w on 2026-06-08T11:04:05Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'testing-u7jy1w'
primary_region = 'ams'

[build]
  dockerfile = 'Dockerfile'

[[mounts]]
  source = 'rrr_scraper_output'
  destination = '/app/output'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 50
    soft_limit = 25

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 2048
